name: Publish to NuGet

on:
  push:
    tags:
      - "v*.*.*" # Run on version tags like v1.2.3
  workflow_dispatch: # Optional manual trigger
    inputs:
      version:
        description: "Version to publish (e.g. 1.2.4)"
        required: true

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

  publish:
    name: Build and Publish to NuGet
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for tag-based versioning

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --output ./artifacts /p:PackageVersion=${GITHUB_REF_NAME#v}

      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
    
      # Push the package
      - name: NuGet push
        run: dotnet nuget push "artifacts/TripNinja.SDK.*.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
